### ISSUE TITLE
@context-file representation of enums and relationships

### ISSUE THREAD

**Issue by Blobonat** [FIWARE/tutorials.Understanding-At-Context#8]
Hi,

I have 2 questions regarding the `@context`-file in this tutorial:

**1.**
In the example the enum-values are included as own entries within the `@context`-file. It is stated:
> If a computer encounters a category=barn then it should be possible to accertain that this category can be identified as a https://wiki.openstreetmap.org/wiki/Tag:building%3Dbarn.

I haven't found any details on expansion of property values in the NGSI-LD API spec v1.3.1. Did I miss smth. or is this just an assumption regarding the Context Broker implementation in this tutorial? Must the enum-values be included in the context?

 **2.**
The `@context`-file includes several relationships, e.g. `"providedBy": "fiware:providedBy"`. In the NGSI-LD API spec v1.3.1. section 4.5.1 regarding the content of the `@context` for an entity it is stated: 
> In addition to the terms defined by the Core NGSI-LD @context (mandatory as per annex B), the @context should contain the following terms:
> [...]
> One term associated to the name of each Relationship used by the entity representation, mapping the Relationship Name with the Relationship Identifier (URI) in the form:
>  - "@type": "@id".
>  - "@id": <Relationship's URI>.

With my understanding this implies that the format used in this tutorial does not follow this specification. Instead of `"providedBy": "fiware:providedBy"` it should be:
```
"providedBy": {
    "@type": "@id",
    "@id": ""fiware:providedBy" }
}
```

**Comment by jason-fox** [comment]
This is probably not clearly explained, but relies on two separate `@context` for normalized NGSI-LD and for key-values representations. Remember the key-values  representation returns JSON-LD, not NGSI-LD since the overall structure is lost.

At the moment (according to 1.5.1 ETSI  Specification).  Attributes are either **Property**, **LanguageProperty** or **Relationship**

- A  **Property** is an object which has a `type` and `value` (which is a JSON-LD `@value`)
- A  **LanguageProperty** is an object which has a `type` and `languageMap` (which is a JSON-LD `@container: @lang`)
- A  **Relationship** is an object which has a `type` and `object` (which is a JSON-LD `@id`).

Therefore for  normalized (and concise) lossless NGSI-LD something like `providedBy` is indeed `"providedBy": "fiware:providedBy"` since it holds an object with a `type` and `object` and not an `@id` directly.

However for key-values `providedBy` does indeed hold a JSON-LD `@id` directly  and the associated JSON-LD context could be defined as:

```json
{
    "providedBy": {
        "@type": "@id",
        "@id": "fiware:providedBy"
     }
}
``` 

The same reasoning occurs with enum values. At the moment a normalized `category` holds  `value` and `type`. If you return key-values you could define:

```json
{
    "category": {
        "@type": "@vocab",
        "@id": "fiware:category"
     }
}
``` 

And the value would be expandable.

Ideally the ETSI spec should be expanded at some point to explicitly deal with a **VocabProperty** which has a `type` and `enum` which is an `@vocab` in which case expanded terms would be dealt with within the broker directly. An some point Orion-LD did this anyway, but it wasn't a correct interpretation of the core `@context` so it was removed.

**Comment by Blobonat** [comment]
@jason-fox thank you for the clarification. I haven't found anything regarding the "normalized" `@context` in the NGSI-LD API spec. All `@context`-examples (e.g. C.2.4) provided in the spec use the JSON-LD representation. Is there any standardized documentation for this?

Also does this imply, that using a JSON-LD `@context` is incorrect when working with the "normalized" representation?

**Comment by jason-fox** [comment]
It is not so much _"normalized `@context`"_ as _"an appropriate `@context` for NGSI-LD output in the normalized form"_.
As explained [here](https://stackoverflow.com/questions/68072065/which-are-the-differences-of-ngsi-ld-and-json-ld/68082837#68082837), NGSI-LD payloads **are** JSON-LD, but the so called "normalized" form is a JSON-LD payload with additional structure rules.

#### "normalized" NGSI-LD 
##### GET `../ngsi-ld/v1/entities/urn:ngsi-ld:Person:John_Lennon` Content-Type: `application/ld+json`

```json
{
   "@context":  [
     "https://json-ld.org/contexts/person.jsonld",
     "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
  ],
   "id": "urn:ngsi-ld:Person:John_Lennon",
   "type": "Person",
   "name": {"type": "Property", "value": "John Lennon"},
   "born": {"type": "Property", "value": "1940-10-09"},
   "spouse": {
      "type": "Relationship", "object":  "urn:ngsi-ld:Person:Cynthia_Lennon"
   }
}
```

This is an NGSI-LD payload in the normalized form, with `type` and `value` - it is valid JSON-LD . The  user's`@context`  describing **Person** could state `"spouse": "https://schema.org/spouse"`. It is used as an input and output format.

#### "key-values" NGSI-LD 
##### GET `../ngsi-ld/v1/entities/urn:ngsi-ld:Person:John_Lennon?options=keyValues` Content-Type: `application/ld+json`

```json
{
  "@context": "https://json-ld.org/contexts/person.jsonld",
  "name": "John Lennon",
  "born": "1940-10-09",
  "spouse": "urn:ngsi-ld:Person:Cynthia_Lennon"
}
```

This is an NGSI-LD output in the key-values form - it is valid JSON-LD,  `type` and `value` are missing.The user's`@context` describing **Person**  could state `"spouse": "https://schema.org/spouse"`  or it could state `"spouse": {"@type": "@id", "@id": "https://schema.org/spouse" }}`.  With [one exception](https://www.youtube.com/watch?v=-XPGyM7K_kU&t=2148s)  it is used as an output format only. Use key-values and annotate extra `@context` information if you are leaving the context broker (the NGSI-LD world) and moving to another process that understands JSON-LD. This key-values could be useful as a notification to a web service for example. Notice how the NGSI-LD core `@context` is not required in this case.

**Comment by Blobonat** [comment]
Thanks a lot. This explanation solved my confusion. The whole `@context` stuff with its role within NGSI-LD is unfortunately not very well explained in the ETSI spec imho.
